models/claim.py
import uuid
from extensions import db


class claim(db.Model):
    __tablename__ = "claims"
    claim_ID = db.Column(db.String(50), primary_key=True, default=lambda: str(uuid.uuid4()))
    userPolicy_ID = db.Column(db.String(50))
    userID = db.Column(db.String(50))
    claimDate = db.Column(db.String(50))
    claimAmount = db.Column(db.String(50))
    claimDescription = db.Column(db.String(555))
    claimStatus = db.Column(db.String(50))

    def to_dict(self):
        return {
            "claim_ID": self.claim_ID,
            "userPolicy_ID": self.userPolicy_ID,
            "userID": self.userID,
            "claimDate": self.claimDate,
            "claimAmount": self.claimAmount,
            "claimDescription": self.claimDescription,
            "claimStatus": self.claimStatus
        }

routes/adminBP.py
from flask import Flask, jsonify, request, render_template, Blueprint
from flask_sqlalchemy import SQLAlchemy
from models.user import User
from models.claim import claim
from models.status import status
from extensions import db
from models.userPolicy import UserPolicy
from routes.policyBP import Policy
from flask_wtf import FlaskForm
from wtforms import StringField,  SubmitField
from wtforms.validators import InputRequired, ValidationError
from flask_login import login_required, current_user

adminBP = Blueprint('adminBP',__name__)

#This URL is resticted only to the admin Site only.
@adminBP.route("/")  # HOF
@login_required
def user_list_page():
    user_list = User.query.all()  # Select * from movies | movie_list iterator
    data = [user.to_dict() for user in user_list]  # list of dictionaries

    #Get your policies
    allPolicy = Policy.query.all()  # Select * from movies | movie_list iterator
    data2 = [policy.to_dict() for policy in allPolicy]  # list of dictionaries
    if current_user.role == 'admin':
        return render_template("admin.html", users=data,policies=data2)
    else:
        message ={
                    "message":"No Access To This Page.",
                    "success":False
                }
        return render_template("success.html",message=message)
 
@adminBP.route("/user/<id>")  # HOF
def user_detail_page(id):
    filtered_user = User.query.get(id)
    #Then you can query the Policies Database base on the ID to find the client's polices
    user_policies = UserPolicy.query.filter_by(userID=id).all()
    #get all status data
    claims = claim.query.filter_by(userID=id).all()
    states = status.query.all()
    pols = policyNames(user_policies,states)
    claims = claimstatus(claims,states)
    #Add the polic Names
    if filtered_user:
        data = filtered_user.to_dict()
        return render_template("userdetailsAdmin.html", user=data,policies =pols,states=states,claims=claims)
    else:
        message ={
          "message":"Error Adding User to DB.",
          "success":False,
          "data":""
          }
        return render_template("success.html", message=message) 
    

@adminBP.route("/approve_policy/<policy_id>", methods=['POST'])
def approve_policy(policy_id):
    if request.method == 'POST':
        policy = UserPolicy.query.get(policy_id)
        if policy:
            policy.status = "3"
            db.session.commit()
        message ={
                    "message":"Policy Approved Successfully.",
                    "success":True,
                    "action":"View User",
                    "URL": f"user/{policy.userID}",
                    "data":policy
                }
        return render_template("success.html",message=message)
    

@adminBP.route("/decline_policy/<policy_id>", methods=['POST'])
def decline_policy(policy_id):
    if request.method == 'POST':
        policy = UserPolicy.query.get(policy_id)
        if policy:
            policy.status = "4"
            db.session.commit()
        message ={
                    "message":"Policy Declined Successfully.",
                    "success":True,
                    "action":"View User",
                    "URL": f"user/{policy.userID}",
                    "data":policy
                }
        return render_template("success.html",message=message)
    
# Claims Aprroval and Decline
@adminBP.route("/approve_claim/<claim_id>", methods=['POST'])
def approve_claim(claim_id):
    if request.method == 'POST':
        claimX = claim.query.get(claim_id)
        if claimX:
            claimX.claimStatus = "3"
            db.session.commit()
        message ={
                    "message":"Policy Approved Successfully.",
                    "success":True,
                    "action":"View User",
                    "URL": f"user/{claimX.userID}",
                    "data":claimX
                }
        return render_template("success.html",message=message)
    
@adminBP.route("/decline_claim/<claim_id>", methods=['POST'])
def decline_claim(claim_id):
    if request.method == 'POST':
        claimX = claim.query.get(claim_id)
        if claimX:
            claimX.claimStatus = "4"
            db.session.commit()
        message ={
                    "message":"Policy Approved Successfully.",
                    "success":True,
                    "action":"View User",
                    "URL": f"user/{claimX.userID}",
                    "data":claimX
                }
        return render_template("success.html",message=message)
#Monthly Premium = (Coverage Value * Risk Assessment Factor) + Administrative Costs + Profit Margin
def calculate_premium(riskFactor,policy):
    cover = policy.coverage
    premium = (cover*riskFactor) + 22 + (cover*riskFactor)*0.20
    return premium

def claimstatus(claims,states):
    newList = []
    for claim in claims:
        C = claim.to_dict()
        C = set_statusC(states,C)
        newList.append(C)
    return newList


def set_status(states,policy):
    policyStatus = policy['status']
    for status in states:
        status = status.to_dict()
        if str(status.get('id')) == policyStatus:
            policy['status'] = status
    return policy

def set_statusC(states,claim):
    claimStatus = claim['claimStatus']
    for status in states:
        status = status.to_dict()
        if str(status.get('id')) == claimStatus:
            claim['claimStatus'] = status
    return claim

def policyNames(user_policies,states):
    newList =[]
    for Userpolicy in user_policies:
        Userpolicy_dict = Userpolicy.to_dict()
        #get the policy
        policy = Policy.query.filter_by(id=Userpolicy.policyID).first()
        Userpolicy_dict['name'] = policy.name
        Userpolicy_dict['description'] = policy.description
        Userpolicy_dict = set_status(states,Userpolicy_dict)
        print(Userpolicy_dict)
        newList.append(Userpolicy_dict)

    return newList


@adminBP.route("/policy/<id>")  # HOF
def policy_detail_page(id):
    filtered_policy = Policy.query.get(id)
    #Then you can query the Policies Database base on the ID to find the client's polices

    if filtered_policy:
        data = filtered_policy.to_dict()
        return render_template("policydetailsAdmin.html", policy=data,user="admin")
    else:
        message ={
                    "message":"Access Denied Successfully.",
                    "success":True,
                    "action":"View User",
                    "URL": f"/",
                    "data":{}
                }
        return render_template("success.html",message=message)   


@adminBP.route("/addUser", methods=["GET"])
def addUserAdmin():
    return render_template("addUser.html")

@adminBP.route("/success", methods=["POST"])  # HOF
def create_user():
    # Get user data from the request form
    first_name = request.form.get("first_name")
    last_name = request.form.get("last_name")
    date_of_birth = request.form.get("date_of_birth")
    phone = request.form.get("phone")
    email = request.form.get("email")
    address = request.form.get("address")
    password = request.form.get("password")

    # Create a new user object
    new_user_data = {
        "first_name": first_name,
        "last_name": last_name,
        "date_of_birth": date_of_birth,
        "phone": phone,
        "email": email,
        "address": address,
        "password": password
    }

    new_user = User(**new_user_data)
    try:
      db.session.add(new_user)
      db.session.commit()
      message ={
          "message":"User Added Successfully.",
          "success":True,
          "data":new_user_data
      }
      return render_template("success.html",message=message)
    except Exception as e:
        db.session.rollback()
        message ={
          "message":"Error Adding User to DB.",
          "success":False,
          "data":str(e)
      }
        return render_template("success.html",message=message)
    

# Adding a New Policy
class PolicyRegistrationForm(FlaskForm):

    policyName = StringField('policyName', validators=[InputRequired()])
    description = StringField('description', validators=[InputRequired()])
    basePremium = StringField('basePremium', validators=[InputRequired()])
    baseCoverge = StringField('baseCoverge', validators=[InputRequired()])
    pictureURL = StringField('imageURL', validators=[InputRequired()])
    
    submit = SubmitField("Sign up")

    #the method will automatically run when  form.validate_on_submit() is run
    def validate_policyName(self, field):
        if Policy.query.filter_by(name=field.data).first():
            raise ValidationError("This policy name is already in use. Please choose a different one.")


@adminBP.route("/register", methods =["GET","POST"])
def register_policy_page():
    
    form = PolicyRegistrationForm()

    if form.validate_on_submit():
        new_policy = Policy(
            name=form.policyName.data,
            description=form.description.data,
            basePremium=form.basePremium.data,
            baseCoverage=form.baseCoverge.data,
            pictureURL=form.pictureURL.data
        )
        try:
            db.session.add(new_policy)
            db.session.commit()
            message ={
                "message":"New Policy Created Successfully.",
                "success":True,
                "action":"View Policy",
                "URL": f"policy/{new_policy.id}",
                "data":new_policy
            }
            return render_template("success.html",message=message)
        except Exception as e:
            db.session.rollback()
            message ={
            "message":"Error Adding Policy to DB.",
            "success":False,
            "data":str(e)
        }
            return render_template("success.html",message=message)
    return render_template("register.html", form =form)


#Approve a policy

templates/addUser.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Document</title>
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <style>
        html,
        body {
            height: 100%;
        }

        .cont {
            margin: 20px 15%;
            align-items: center;
            justify-content: center;
        }
    </style>
</head>

<body>
    <div class="cont">
        <form class="addUser" action="{{ url_for('adminBP.create_user') }}" method="POST">
            <div>
                <h1>Add New Customer</h1>
                <p class="clientsNo">Fill out all required fields to create a new customer</p>
            </div>
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">First Name</label>
                <input type="text" class="form-control" name="first_name" placeholder="James">
            </div>
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Last Name</label>
                <input type="text" class="form-control" name="last_name" placeholder="Khumalo">
            </div>
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Date of Birth</label>
                <input type="date" class="form-control" name="date_of_birth" placeholder="YYYY/MM/DD"
                    pattern="\d{4}-\d{2}-\d{2}">
            </div>
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Phone Number</label>
                <input type="tel" class="form-control" name="phone" placeholder="072 123 4567">
            </div>
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Address</label>
                <input type="tel" class="form-control" name="address"
                    placeholder="123 Street Name, City, State, Zip Code">
            </div>
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Email address</label>
                <input type="email" class="form-control" name="email" placeholder="notion@exa.com">
            </div>
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Password</label>
                <input type="password" class="form-control" name="password">
            </div>
            <button type="submit" class="btn btn-secondary" style="background: #26a69a;border:none;">Create
                User</button>
    </div>
    </form>


    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>

</html>

templates/admin.html
{% extends "base.html" %}

{% block title %}MiWayCyber{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
<section class="cont">
    <div class="header">
        <h1>Clients</h1>
        <p class="clientsNo">{{users|length - 1}}</p>
    </div>
    <div class="clients">
        {% for user in users if user.role == 'client'%}
        <div class="client">
            <img class="profilePicture"
                src="https://profilemagazine.com/wp-content/uploads/2020/04/Ajmere-Dale-Square-thumbnail.jpg" alt="">
            <p class="name">{{user.first_name}} {{user.last_name}}</p>
            <div class="boxes">
                <p class="box">
                    C{{ user.id}}
                </p>
                <p class="box" style="background: #D9D9D9;">
                    Active client
                </p>
            </div>
            <p class="pNomarl" style="text-decoration-line: underline;">{{user.email}}</p>
            <p class="pNomarl">{{user.phone}}</p>
            <p class="address">{{user.address}}</p>
            <div class="buttons">
                <a href="/admin/user/{{ user.id }}" class="button">View</a>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="buttons">
        <a href="/register" class="button">+ add New User</a>
    </div>
</section>
<section class="cont">
    <div class="header">
        <h1>Policies</h1>
        <p class="clientsNo">{{policies|length}}</p>
    </div>
    <div class="policies2">
        {% for policy in policies %}
        <div class="policy2">
            <div>
                <img class="policyImg" src={{policy.pictureURL}} alt="">
            </div>
            <div style="padding: 10px;">
                <p class="name">{{policy.name}}</p>
                <p class="address">{{policy.description}}</p>

                <p class="fromPrice">from</p>
                <p class="price">R{{policy.basePremium}}</p>
                <p class="fromPrice">Coverage starts at R{{policy.baseCoverage}}</p>
            </div>
            <div class="buttons">
                <a href="/admin/policy/{{ policy.id }}" class="button">View</a>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="buttons">
        <a href="/admin/register" class="button">+ add New Policy</a>
    </div>
</section>
<section class="cont">
    <div class="header">
        <h1>Reports</h1>
        <p class="clientsNo">0</p>
    </div>
</section>
{% endblock %}

templates/applyPolicy.html
{% extends "base.html" %}

{% block title %}MiWayCyber{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
<h1>User Policy Form</h1>
<form method="POST" action="">
    {{ form.csrf_token }}
    <div class="form-group">
        {{ form.policyID.label }}
        {{ form.policyID(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.coverage.label }}
        {{ form.coverage(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.startDate.label }}
        {{ form.startDate(class="form-control", type="date") }}
    </div>
    <div class="form-group">
        {{ form.endDate.label }}
        {{ form.endDate(class="form-control", type="date") }}
    </div>
    <div class="form-group">
        {{ form.assetValue.label }}
        {{ form.assetValue(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.assetDescription.label }}
        {{ form.assetDescription(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.assetSecurity.label }}
        {{ form.assetSecurity(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.clientDeclaration(class="form-check-input") }}
        {{ form.clientDeclaration.label(class="form-check-label") }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
        rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>{% block title %}My Website{% endblock %}</title>
    <meta name="viewport" content="width=S, initial-scale=1.0">
    {% block styleTag%} 
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    {% endblock %}
    <script src="https://kit.fontawesome.com/0fa3348648.js" crossorigin="anonymous"></script>
    {% block style %}My Website{% endblock %}
  </head>

<body>
  <section class="Boday">
    <div>

    
    <nav class="navbar navbar-expand-lg custom-navbar-color">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img src="{{ url_for('static', filename='miway.png') }}" alt="Logo"  height="30" class="d-inline-block align-top">
          Cyber
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/">Insurance</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/register">Apply</a>
            </li>
          </ul>
          {% if current_user.is_authenticated %}
            {% if current_user.role == 'admin'%}
            <a href="/admin" class="btn btn-primary">Admin</a>
            {% else %}
            <a href="/user/{{current_user.id}}" class="btn btn-light">Profile</a>
            {% endif %}
            <a href="{{url_for('logout')}}" class="btn btn-light">log Out</a>
          {% else %}
          <a href="/login" class="btn btn-primary">Log In</a>
          {% endif %}
        </div>
      </div>
    </nav>
  </div>

      {% block content %}
      <!-- Default content goes here if not overridden -->
      {% endblock %}

<div>
    <section class="footer">
      <img src="{{ url_for('static', filename='miway.png') }}" alt="">
      <div>
        <i class="fa-brands fa-instagram"></i>
        <i class="fa-brands fa-facebook"></i>
        <i class="fa-brands fa-twitter"></i>
      </div>
      <div>
        <p>Copyright © MiWay is a licensed non-life insurer and Financial Services Provider (FSP 33970). Ts & Cs apply.</p>
      </div>
    </section>
  </div>
</section>

    
    
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</html>

templates/claim.html
{% extends "base.html" %}

{% block title %}MiWayCyber{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
<h1>Create New Claim</h1>
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <div>
        {{ form.userPolicy.label }} {{ form.userPolicy }}
        {% if form.userPolicy.errors %}
            {% for error in form.userPolicy.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}
        {% endif %}
    </div>
    <div>
        <label for="claimDate">{{ form.claimDate.label }}</label>
        <input type="date" id="claimDate" name="claimDate">
        {% if form.claimDate.errors %}
            {% for error in form.claimDate.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}
        {% endif %}
    </div>
    <div>
        {{ form.claimAmount.label }} {{ form.claimAmount }}
        {% if form.claimAmount.errors %}
            {% for error in form.claimAmount.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}
        {% endif %}
    </div>
    <div>
        {{ form.claimDescription.label }} {{ form.claimDescription }}
        {% if form.claimDescription.errors %}
            {% for error in form.claimDescription.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}
        {% endif %}
    </div>
    {{ form.submit(class="btn btn-primary") }}
</form>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}MiWayCyber{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
<div class="landing">
    <div class="words">
        <p class="pwelcome">Welcome to MiwayCyber</p>
        <p class="wordsLand">Insurance coverage to digital assets such as cryptocurrencies, digital identity, and data
            privacy. </p>
        <div>
            <button class="btn btn-primary" style="background-color: #e0004d; /* Green */
                border-color: #e0004d;">MiWay</button>
                <a href="/register" class="btn btn-primary">Register</a>
        </div>

    </div>
    <div class="image">
        <img class="person"
            src="https://smallbizclub.com/wp-content/uploads/2021/07/bigstock-Serious-Business-Man-Trader-An-394931603.jpg"
            alt="">
    </div>
</div>
<div class="aboutUS"  id="services">
    <div class="image2">
        <div class="service">
            <i class="fa-brands fa-bitcoin fa-3x" style="color: #e0004d;"></i>
            <h6 class="hgservices">Digital Asset Protection</h6>
            <p class="pservices">Insurance coverage for digital assets such as cryptocurrencies, digital tokens, and virtual currencies against theft, unauthorized access, or damage</p>
        </div>
        <div class="service" style="background-color: #e0004d;">
            <i class="fa-solid fa-fingerprint fa-3x" style="color: #ecebeb;"></i>
            <h6 class="hgservices" style="color: #ecebeb;">Digital Identity Protection</h6>
            <p class="pservices" style="color: #ecebeb;" >Insurance coverage for financial losses resulting from identity theft in digital spaces, including unauthorized use of personal information for fraudulent activities</p>
        </div>
        <div class="service">
            <i class="fa-solid fa-user-shield fa-3x" style="color: #e0004d;"></i>
            <h6 class="hgservices">Data Privacy Insurance</h6>
            <p class="pservices">Insurance coverage for liabilities arising from data breaches, violations of privacy laws and regulations, and cyber-attacks targeting sensitive information</p>
        </div>
        <div class="service">
            <i class="fa-solid fa-magnifying-glass fa-3x" style="color: #e0004d;"></i>
            <h6 class="hgservices">Assess Risk and Underwriting</h6>
            <p class="pservices">Thorough risk assessment and underwriting services to evaluate the level of risk associated with insuring digital assets, digital identity, and data privacy.</p>
        </div>
        

    </div>
    <div class="words2">
        <p class="serviceTitle"><span><i class="fa-solid fa-arrow-left fa-0.5x"></i></span> Our Services</p>
        <div class="para">
            <p class="paraServices">We offer these comprehensive services, with the aim to support individuals and organizations in effectively managing the financial risks associated with digital assets, digital identity, and data privacy in today's interconnected and data-driven business environment.</p>
            <img style="width: 250px;" src="https://th.bing.com/th/id/R.890eef73dc8197e12bcefa4b46bb69f9?rik=75%2bPnFWOL6Z7oA&pid=ImgRaw&r=0" alt="">
        </div>
    </div>
</div>
<div class="products">
    <div class="policyWords">
        <div>
            <p class="serviceTitle" style="text-align: center;" ><span><i class="fa-solid fa-arrow-left fa-0.5x"></i></span> Our Policies</p>
        </div>
        <div class="para">
            <p class="paraServices" style="text-align: center;">We specialize in safeguarding your digital assets, identity, and privacy with tailored insurance solutions. Count on us to protect you from cyber threats and financial losses in the digital era.</p>
        </div>
    </div>
    <div class="policies3">
        {% for policy in policies %}
        <div class="policy2" style="margin-bottom: 30px;">
            <div>
                <img class="policyImg" src={{policy.pictureURL}} alt="">
            </div>
            <div style="padding: 10px;">
                <p class="name">{{policy.name}}</p>
                <p class="address">{{policy.description}}</p>

                <p class="fromPrice">from</p>
                <p class="price">R{{policy.basePremium}}</p>
                <p class="fromPrice">Coverage starts at R{{policy.baseCoverage}}</p>
            </div>
            <div class="buttons">
                <a href="/userpolicy/{{ policy.id }}" class="button">View More</a>
            </div>
        </div>
        {% endfor %}
    </div>
    
</div>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}MiWayCyber{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
<form method="POST" action="">
    {{ form.hidden_tag() }}

    {% if form.firstname.errors %}
        {% for error in form.firstname.errors %}
            <div style="color: crimson;">{{ error }}</div>
        {% endfor %}
    {% endif %}
    <div class="form-group">
        {{ form.firstname.label }}:{{ form.firstname(placeholder="First Name", class="form-control") }}
        <br>
    </div>

    {% if form.lastname.errors %}
        {% for error in form.lastname.errors %}
            <div style="color: crimson;">{{ error }}</div>
        {% endfor %}
    {% endif %}
    <div class="form-group">
        {{ form.lastname.label }}:{{ form.lastname(placeholder="Last Name", class="form-control") }}
        <br>
    </div>

    {% if form.password.errors %}
        {% for error in form.password.errors %}
            <div style="color: crimson;">{{ error }}</div>
        {% endfor %}
    {% endif %}
    <div class="form-group">
        {{ form.password.label }}:{{ form.password(placeholder="Password", class="form-control") }}
        <br>
    </div>

    {{ form.submit(class="btn btn-primary") }}
</form>
<div>
    <p>Register for <a href="/register">MiWayCyber</a> here</p>
</div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}MiWayCyber{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
<h1>Register New User</h1>
<form method="POST" action="">
    {{ form.hidden_tag() }}

    {% for field in form if field.type != 'SubmitField' %}
            {% if field.name == 'date_of_birth' %}
            {{ field.label }}: <input type="date" name="{{ field.name }}" placeholder="{{ field.label.text }}" {% if field.data %}value="{{ field.data.strftime('%Y-%m-%d') }}"{% endif %} required>
            {% endif %}
            {% if field.errors %}
            {% for error in field.errors %}
                <div style="color: crimson;">{{ error }}</div>
            {% endfor %}
            {% endif %}
        
        {{ field.label }}: {{ field(placeholder=field.label.text,class_="form-control") }}
        <br>
    {% endfor %}

    {{ form.submit(class="btn btn-primary") }}
</form>
{% endblock %}

templates/registerPolicy.html
{% extends "base.html" %}

{% block title %}MiWayCyber{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
<h1>Register New Policy</h1>
<form method="POST" action="">
    {{ form.hidden_tag() }}

    {% for field in form %}
        {% if field.errors %}
            {% for error in field.errors %}
                <div style="color: crimson;">{{ error }}</div>
            {% endfor %}
        {% endif %}
        
        {{ field.label }}: {{ field(placeholder=field.label.text) }}
        <br>
    {% endfor %}

    {{ form.submit() }}
</form>
{% endblock %}

templates/success.html
{% extends "base.html" %}

{% block title %}MiWayCyber{% endblock %}
{% block content %}
<div class="imgs">
    <img src="https://smallbizclub.com/wp-content/uploads/2021/07/bigstock-Serious-Business-Man-Trader-An-394931603.jpg" alt="">
</div>
<section class="success-cont">
    <div class="success">
        <h1>{{message.message}}</h1>
        <p class="pNormal">{{message.data}}</p>
        <div>
            <button type="submit" class="btn btn-secondary" style="background: #26a69a;border:none;">
                <a href="/" style="text-decoration: none; color: inherit;">
                    <span style="margin-right: 5px;">&larr;</span>Home
                </a>
            </button>
            {% if message.success%}
            <button type="submit" class="btn btn-secondary" style="background: #26a69a;border:none;">
                <a href="/admin/{{ message.URL }}" style="text-decoration: none; color: inherit;">{{ message.action }}
                </a>
            </button>
            {% endif %}
        </div>

    </div>
</section>
{% endblock %}